version: '3.9'
services:
  dev:
    container_name: crud-example-dev
    image: crud-example-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    networks:
      - server-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      MONGO_URL: mongodb://root:pass12345@mongodb:27017

  mongodb:
    image: mongo:7.0
    container_name: mongodb-srv
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass12345
    networks:
      - server-network
    ports:
      - 27018:27017
    restart: unless-stopped

networks:
  server-network:
